export const PriceTextTokens = [
  {
    cardPrice: "br. 4000ft / fő / óra",
    tableTitle: "Általános takarítás",
    tableDescription:
      ["Az Általános takarítási szolgáltatásunkban a leggyakoribb otthoni takarítási feladatokat végezzük el. Ide tartozik a nagyobb tárgyakon való portörlés, mint például bútorokon, valamint a porszívózás és a felmosás. Emellett gondoskodunk a csempék, mosdókagylók, zuhanytálca és kád tisztításáról, valamint a WC teljes körű takarításáról. Szolgáltatásunk része továbbá a tűzhely és a mikrohullámú sütő kisebb takarítása is.", "Fontos kiemelni, hogy mindezeket a feladatokat képzett csapatunkkal végezzük, akik hatékonyan dolgoznak és kiváló minőségű munkát nyújtanak. Az ár 4000 Ft/fő/óra, és a takarítást mindig ketten végzik,  mivel így nemcsak hatékonyabbak vagyunk, hanem időt is spórolunk mindannyiunk számára. Hiszünk  abban, hogy a csapatmunka segítségével jobb eredményeket érhetünk el, és minden ügyfelünk  elégedett lesz a végeredménnyel.","  Bízunk benne, hogy ezekkel a szolgáltatásokkal otthona tiszta és friss lesz, így Önnek csak a  kényelmes otthon élvezetére kelljen koncentrálnia."],
    tableData: [
      { service: "Pókhálózás", included: true },
      { service: "Portörlés (nagyobb tárgyak pl.:bútorok)", included: true },
      { service: "Porszívózás", included: true },
      { service: "Felmosás", included: true },
      { service: "Mosogatás", included: false },
      { service: "Mosás", included: false },
      { service: "Csempe felületek tisztítása", included: true },
      { service: "Mosdókagylók tisztítása", included: true },
      { service: "Zuhanytálca tisztítása", included: true },
      { service: "Kád tisztítása", included: true },
      { service: "WC tisztítása", included: true },
      { service: "Ajtók takarítása", included: false },
      { service: "Ajtókeretek takarítása", included: false },
      { service: "Bútorok takarítása (ápolása)", included: false },
      { service: "Kapcsolók/konnektorok takarítása", included: false },
      { service: "Kilincsek takarítása", included: false },
      { service: "Ablak tisztítás", included: false },
      { service: "Ablakkeret tisztítás", included: false },
      { service: "Függöny mosás", included: false },
      { service: "Csapok, zuhanyfej vízkőtelenítése", included: false },
      { service: "Tűzhely kisebb tisztítása", included: true },
      {
        service: "Tűzhely és sütő zsírtalanítása (nagyobb tisztítása)",
        included: false,
      },
      { service: "Mikrohullámú sütő kisebb takarítása", included: true },
      {
        service: "Mikrohullámú sütő zsírtalanítása (nagyobb tisztítása)",
        included: false,
      },
      { service: "Helységek szegélyeinek takarítása", included: false },
      {
        service: "Tárgyak portörlése (kisebb tárgyak pl.:csetreszek)",
        included: false,
      },
    ],
  },
  {
    cardPrice: "br. 5200ft / fő / óra",
    tableTitle: "Nagytakarítás",
    tableDescription:
      ["Nagytakarítás során az első alkalom mindig különleges, hiszen egy olyan folyamatról van szó, mely során a tisztaság szempontjából kissé elhanyagolt ház vagy lakás újra ragyogni kezd. A pókhálózások eltűnnek, a por leülepedésének nyoma sem marad, és minden felület újra frissen csillog.","","  Az első lépés általában a portörlés, mely során a nagyobb tárgyakat, például bútorokat gondosan áttörlik. Ezután következik a porszívózás, mely során alaposan megtisztítják a padlót és a szőnyegeket. A felmosás pedig friss illatot varázsol a lakásba.","","  A mosogatás és mosás nem csak a konyhai területre korlátozódik, hanem az egész lakásra kiterjed. A csempék, mosdókagylók, zuhanytálca és kád alapos tisztítása alapvető lépés a higiénia megőrzése érdekében. A WC körültekintő tisztítása különösen fontos, hogy a fertőzés kockázatát minimalizálják.  Az ajtók, ajtókeretek és bútorok takarítása nemcsak esztétikailag fontos, hanem az élettartamuk meghosszabbítása érdekében is. A kapcsolók, konnektorok és kilincsek tisztán tartása pedig hozzájárul a lakás általános higiéniai szintjének fenntartásához.",""," Az ablakok és ablakkeretek tisztítása a friss levegő beengedésének és a kilátás élvezetének  elősegítése érdekében fontos. A függönyök mosása és a csapok, zuhanyfej vízkőtelenítése pedig további aprólékos munkát igényel, de elengedhetetlen a tiszta környezet megteremtéséhez. A konyhai terület külön figyelmet igényel. A tűzhely és sütő alapos zsírtalanítása, valamint a mikrohullámú sütő tisztítása elengedhetetlen a higiéniai követelmények teljesítése érdekében. Végül, a helységek szegélyeinek és a kisebb tárgyak, például csetreszek portörlése zárja a takarítási folyamatot, melynek során minden apró részletre odafigyelnek."],
    tableData: [
      { service: "Pókhálózás", included: true },
      { service: "Portörlés (nagyobb tárgyak pl.:bútorok)", included: true },
      { service: "Porszívózás", included: true },
      { service: "Felmosás", included: true },
      { service: "Mosogatás", included: true },
      { service: "Mosás", included: true },
      { service: "Csempe felületek tisztítása", included: true },
      { service: "Mosdókagylók tisztítása", included: true },
      { service: "Zuhanytálca tisztítása", included: true },
      { service: "Kád tisztítása", included: true },
      { service: "WC tisztítása", included: true },
      { service: "Ajtók takarítása", included: true },
      { service: "Ajtókeretek takarítása", included: true },
      { service: "Bútorok takarítása (ápolása)", included: true },
      { service: "Kapcsolók/konnektorok takarítása", included: true },
      { service: "Kilincsek takarítása", included: true },
      { service: "Ablak tisztítás", included: true },
      { service: "Ablakkeret tisztítás", included: true },
      { service: "Függöny mosás", included: true },
      { service: "Csapok, zuhanyfej vízkőtelenítése", included: true },
      { service: "Tűzhely kisebb tisztítása", included: true },
      {
        service: "Tűzhely és sütő zsírtalanítása (nagyobb tisztítása)",
        included: true,
      },
      { service: "Mikrohullámú sütő kisebb takarítása", included: true },
      {
        service: "Mikrohullámú sütő zsírtalanítása (nagyobb tisztítása)",
        included: true,
      },
      { service: "Helységek szegélyeinek takarítása", included: true },
      {
        service: "Tárgyak portörlése (kisebb tárgyak pl.:csetreszek)",
        included: true,
      },
    ],
  },
  {
    cardPrice: "br. 6100-8700ft / fő / óra",
    tableTitle: "Extrém nagytakarítás",
    tableDescription:
      ["Az extrém takarítás olyan kihívást jelent, amelyben a gyűjtögető életmód által felhalmozódott hulladék és szemét teljes megsemmisítésére vagy átalakítására törekszünk. Az ilyen típusú takarítás során a nem használt tárgyak nagy mennyiségével és az elhanyagolt élettérrel kell megbirkózni. A rendkívül elhanyagolt életterekben gyakran szembe találjuk, magunkat szemét heggyel, amelyek között már alig lehet látni a padlót és közlekedni is nehezen lehet. Az extrém takarítás során a cél az, hogy ezeket a területeket megtisztítsák és rendezetté tegyék, megteremtve ezzel az egészséges és élhető környezetet."," Ez a fajta takarítás rendkívüli odafigyelést, erőfeszítést és szakértelmet igényel. A takarítóknak nem csak a felhalmozott szemetet és hulladékot kell eltávolítaniuk, hanem meg kell oldaniuk az esetleges szagproblémákat, fertőtleníteniük kell a felületeket, és vissza kell állítaniuk az élettér funkcionalitását."," Az extrém takarítás ára általában az elvégzendő munka mennyiségétől és a szükséges erőforrásoktól függ. A takarítás összköltsége általában 6100 forinttól egészen 8700 forintig terjedhet, attól függően hogy mekkora területet kell kitakarítani és milyen mértékű a rendrakás szükségessége."],
    tableData: [
      { service: "Pókhálózás", included: true, isFluidPrice: true },
      {
        service: "Portörlés (nagyobb tárgyak pl.:bútorok)",
        included: true,
        isFluidPrice: true,
      },
      { service: "Porszívózás", included: true, isFluidPrice: true },
      { service: "Felmosás", included: true, isFluidPrice: true },
      { service: "Mosogatás", included: true, isFluidPrice: true },
      { service: "Mosás", included: true, isFluidPrice: true },
      {
        service: "Csempe felületek tisztítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Mosdókagylók tisztítása",
        included: true,
        isFluidPrice: true,
      },
      { service: "Zuhanytálca tisztítása", included: true, isFluidPrice: true },
      { service: "Kád tisztítása", included: true, isFluidPrice: true },
      { service: "WC tisztítása", included: true, isFluidPrice: true },
      { service: "Ajtók takarítása", included: true, isFluidPrice: true },
      { service: "Ajtókeretek takarítása", included: true, isFluidPrice: true },
      {
        service: "Bútorok takarítása (ápolása)",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Kapcsolók/konnektorok takarítása",
        included: true,
        isFluidPrice: true,
      },
      { service: "Kilincsek takarítása", included: true, isFluidPrice: true },
      { service: "Ablak tisztítás", included: true, isFluidPrice: true },
      { service: "Ablakkeret tisztítás", included: true, isFluidPrice: true },
      { service: "Függöny mosás", included: true, isFluidPrice: true },
      {
        service: "Csapok, zuhanyfej vízkőtelenítése",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Tűzhely kisebb tisztítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Tűzhely és sütő zsírtalanítása (nagyobb tisztítása)",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Mikrohullámú sütő kisebb takarítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Mikrohullámú sütő zsírtalanítása (nagyobb tisztítása)",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Helységek szegélyeinek takarítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Tárgyak portörlése (kisebb tárgyak pl.:csetreszek)",
        included: true,
        isFluidPrice: true,
      },
    ],
  },
  {
    cardPrice: "br. 6100-8700ft / fő / óra",
    tableTitle: "Felújítás utáni nagytakarítás",
    tableDescription:
      ["A felújítás utáni takarítás az építkezés után rendszerint szükséges, hogy a frissített tér újra tiszta és lakható legyen. Ez a folyamat különösen fontos, mivel az építkezési munkák során számos lerakódás és piszok keletkezik, mint például festék foltok és cseppek, építési por, vakolatdarabok stb.", "A festék foltok és cseppek eltávolítása általában az egyik legelső lépés a felújítás utáni takarítás során. Ez lehet festékmaradvány a falakon, a padlón, ablakon vagy akár a bútorokon is. Ezeket a foltokat alaposan el kell távolítani a felületekről, hogy a tér újra friss és esztétikus legyen. Az építési por szintén jelentős problémát jelenthet, mivel beleül a felületek pórusaiba és nehezen eltávolítható. A felújítás utáni takarítás során alaposan meg kell tisztítani minden felületet a por lerakódásától, beleértve a falakat, a padlókat, az ablakokat és az ajtókat is.","Az ilyen jellegű takarítás komoly erőfeszítést, és gyakran speciális eszközöket és tisztítószereket is igényel. A szakszerű takarítás és a megfelelő felszerelés használata létfontosságú a felújítás utáni tiszta és rendezett tér eléréséhez",  "Az árak a felújítás utáni takarítás esetén változóak lehetnek, attól függően, hogy mennyi munkát és erőforrást igényel a takarítás. Ára 6100 Ft-tól egészen 8700 Ft-ig terjed, attól függően, hogy mekkora területet kell kitakarítani és milyen nehézségekkel kell megküzdeni a piszok és a foltok eltávolítása során."],
    tableData: [
      { service: "Pókhálózás", included: true, isFluidPrice: true },
      {
        service: "Portörlés (nagyobb tárgyak pl.:bútorok)",
        included: true,
        isFluidPrice: true,
      },
      { service: "Porszívózás", included: true, isFluidPrice: true },
      { service: "Felmosás", included: true, isFluidPrice: true },
      { service: "Mosogatás", included: true, isFluidPrice: true },
      { service: "Mosás", included: true, isFluidPrice: true },
      {
        service: "Csempe felületek tisztítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Mosdókagylók tisztítása",
        included: true,
        isFluidPrice: true,
      },
      { service: "Zuhanytálca tisztítása", included: true, isFluidPrice: true },
      { service: "Kád tisztítása", included: true, isFluidPrice: true },
      { service: "WC tisztítása", included: true, isFluidPrice: true },
      { service: "Ajtók takarítása", included: true, isFluidPrice: true },
      { service: "Ajtókeretek takarítása", included: true, isFluidPrice: true },
      {
        service: "Bútorok takarítása (ápolása)",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Kapcsolók/konnektorok takarítása",
        included: true,
        isFluidPrice: true,
      },
      { service: "Kilincsek takarítása", included: true, isFluidPrice: true },
      { service: "Ablak tisztítás", included: true, isFluidPrice: true },
      { service: "Ablakkeret tisztítás", included: true, isFluidPrice: true },
      { service: "Függöny mosás", included: true, isFluidPrice: true },
      {
        service: "Csapok, zuhanyfej vízkőtelenítése",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Tűzhely kisebb tisztítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Tűzhely és sütő zsírtalanítása (nagyobb tisztítása)",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Mikrohullámú sütő kisebb takarítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Mikrohullámú sütő zsírtalanítása (nagyobb tisztítása)",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Helységek szegélyeinek takarítása",
        included: true,
        isFluidPrice: true,
      },
      {
        service: "Tárgyak portörlése (kisebb tárgyak pl.:csetreszek)",
        included: true,
        isFluidPrice: true,
      },
    ],
  },
 
  {
    cardPrice: "br. 4450ft / fő / óra",
    tableTitle: "Gépi gőztisztítás",
    tableDescription: ["A gépi gőztisztítás egy hatékony és környezetbarát módszer a szennyeződések eltávolítására számos felületről, beleértve a konyhát, fürdőszobát is. Ez a technika forró gőzt használ, amely képes áthatolni a szálak között és feloldani a makacs szennyeződéseket. A gőz emellett természetes fertőtlenítő hatással is rendelkezik, így segít megsemmisíteni a baktériumokat és allergéneket is. Azonban fontos megjegyezni, hogy a gépi gőztisztításnak is vannak korlátai, például a nagyon makacs foltok esetén lehet, hogy több alkalommal kell alkalmazni, és bizonyos típusú anyagokra nem ajánlott. Általában azonban ez a módszer hatékony és kíméletes megoldás a háztartási tisztítási feladatokhoz."],
    tableData: [
      { service: "Gépi gőztisztítás", included: true }]
  },
  {
    cardPrice: "br. 5750ft / fő / óra",
    tableTitle: "Szőnyeg- és Kárpittisztítás",
    tableDescription: ["A gépi szőnyegtisztítás hatékony és gyors megoldást kínál szőnyegeinkben megbújó szennyeződések és foltok eltávolítására. A gépek alaposan tisztítják a szálakat, mélyre hatolva kiszedik a makacs szennyeződéseket is. Ugyanakkor, néha előfordulhat, hogy néhány folt nem távozik teljesen. Fontos tehát, hogy előzetesen felmérjük a szőnyeg állapotát, és reálisan beállítsuk az elvárásainkat a tisztítás eredményeivel kapcsolatban."],
    tableData: [
      { service: "Szőnyeg- és Kárpittisztítás", included: true }]
  },
];
